export const plansDummy = [
  {
    name: "Free Plan",
    id: 1,
    interval: "month",
    is_active: true,
    created_at: "2023-01-15T10:00:00Z",
    amount: 0,
    is_stripe_plan: false,
    current_plan: false,
    video_length: 10,
    face_detection: 3,
    transitions: 5,
    watermarking: false,
    chunk_size: 10,
    ai_model: "lowest",
    output_resolution: "480p",
    video_summarization: 3,
    file_retention_policy: 7,
    storage_space: 5,
    priority: "low",
    notification_system: "Basic notifications",
  },
  {
    name: "Pro Plan",
    id: 2,
    interval: "month",
    is_active: true,
    created_at: "2023-02-20T12:30:00Z",
    amount: 30,
    is_stripe_plan: true,
    current_plan: true,
    video_length: 60,
    face_detection: 5,
    transitions: 10,
    watermarking: true,
    chunk_size: 20,
    ai_model: "medium",
    output_resolution: "720p",
    video_summarization: 10,
    file_retention_policy: 30,
    storage_space: 50,
    priority: "medium",
    notification_system: "Pro notifications",
  },
  {
    name: "Enterprise Plan",
    id: 3,
    interval: "month",
    is_active: true,
    created_at: "2023-03-10T15:45:00Z",
    amount: 100,
    is_stripe_plan: true,
    current_plan: false,
    video_length: 120,
    face_detection: 7,
    transitions: 15,
    watermarking: true,
    chunk_size: 30,
    ai_model: "high",
    output_resolution: "1080p",
    video_summarization: 15,
    file_retention_policy: 60,
    storage_space: 100,
    priority: "high",
    notification_system: "Enterprise notifications",
  },
];
